include:
  - ./postgres/postgres.yml
  - ./dish_as_a_service_backend/dish_as_a_service.yml
  - ./dish_as_a_service_frontend/dish_as_a_service.yml
  - ./storage_service/storage_service.yml
  - ./tracing_service/tracing_service.yml

networks:
  gateway_network:
    driver: bridge
    name: "gateway_network"

services:
  gateway:
    image: nginx
    hostname: gateway
    ports:
      - 80:80
      - 443:443
    networks:
      - gateway_network
    volumes:
      - .nginx/:/etc/nginx
      - ./certs:/certs/:ro
    deploy:
      restart_policy:
        condition: unless-stopped
    depends_on:
      #-----------------services-----------------
      storage_service:
        condition: service_started
      dish_as_a_service:
        condition: service_started
      dish_as_a_service_frontend:
        condition: service_started
      #------------------------------------------
      pg_admin:
        condition: service_started
      grafana:
        condition: service_started
