version: "3.8"
include:
  - ../postgres/postgres.yml

services:
  dish_as_a_service:
    hostname: dish_as_a_service
    image: falokut/dish_as_a_service_backend-alpine:latest
    expose:
      - 8080
    networks:
      - postgres_network
      - gateway_network
    volumes:
      - ./config.yml/:/conf/config.yml
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      APP_ADMIN_SECRET: ${ADMIN_SECRET}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TG_BOT_PAYMENT_TOKEN: ${TG_BOT_PAYMENT_TOKEN}
    depends_on:
      postgres:
        condition: service_started
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: unless-stopped
    labels:
      servicename: "dish_as_a_service"
      org.label-schema.group: "monitoring"
