name: Build backend docker image

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  buld-and-push-service-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish backend to Registry
        uses: docker/build-push-action@v5
        with:
          context: backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: falokut/dish_as_a_service_backend-alpine:latest
          labels: ${{ steps.meta.outputs.labels }}
